In [52]:
import numpy as np


In [54]:
arr=np.array([
    [1,4335],
    [2,9552],
    [3,7332],
    [4,4504],
    [5,5335],
    [6,7552],
    [7,8332],
    [8,6504],
    [9,8969],
    [10,7689]])

In [55]:
print(arr)

[[   1 4335]
 [   2 9552]
 [   3 7332]
 [   4 4504]
 [   5 5335]
 [   6 7552]
 [   7 8332]
 [   8 6504]
 [   9 8969]
 [  10 7689]]


In [68]:
arr[:,1]+=1000

In [69]:
arr[:,1]>7000

array([False,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [70]:
arr[arr[:,1]>7000]

array([[    2, 11552],
       [    3,  9332],
       [    5,  7335],
       [    6,  9552],
       [    7, 10332],
       [    8,  8504],
       [    9, 10969],
       [   10,  9689]])

In [ ]:
np.sort(arr[:,1])

array([ 6335,  6504,  7335,  8504,  9332,  9552,  9689, 10332, 10969,
       11552])

: 